// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// biome-ignore lint/complexity/noBannedTypes:
type CloudflareBindings = {
	TURSO_CONNECTION_URL: string;
	TURSO_AUTH_TOKEN: string;
};
