// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
type Env = {
	SP_API_CLIENT_ID: string;
	SP_API_CLIENT_SECRET: string;
	AMAZON_CLIENT_ID: string;
	AMAZON_CLIENT_SECRET: string;
	TURSO_CONNECTION_URL: string;
	TURSO_AUTH_TOKEN: string;
};
