name: Deploy Web

on:
  push:
    branches:
      - 'front-workflow'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install
      - name: Install dependencies with Bun
        run: ~/.bun/bin/bun install

      - name: change folder
        run: cd web

      - name: Build with Bun
        run: ~/.bun/bin/bun install run build